reviewsdb:
  image: mysql:5.7.21
  volumes:
    - ./preparedb.sql:/docker-entrypoint-initdb.d/preparedb.sql
    - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: reviews
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin123
    MYSQL_ROOT_PASSWORD: admin123